require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe MentorshipsessionsController do

  # This should return the minimal set of attributes required to create a valid
  # Mentorshipsession. As you add validations to Mentorshipsession, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "mentor_id" => "" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # MentorshipsessionsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all mentorshipsessions as @mentorshipsessions" do
      mentorshipsession = Mentorshipsession.create! valid_attributes
      get :index, {}, valid_session
      assigns(:mentorshipsessions).should eq([mentorshipsession])
    end
  end

  describe "GET show" do
    it "assigns the requested mentorshipsession as @mentorshipsession" do
      mentorshipsession = Mentorshipsession.create! valid_attributes
      get :show, {:id => mentorshipsession.to_param}, valid_session
      assigns(:mentorshipsession).should eq(mentorshipsession)
    end
  end

  describe "GET new" do
    it "assigns a new mentorshipsession as @mentorshipsession" do
      get :new, {}, valid_session
      assigns(:mentorshipsession).should be_a_new(Mentorshipsession)
    end
  end

  describe "GET edit" do
    it "assigns the requested mentorshipsession as @mentorshipsession" do
      mentorshipsession = Mentorshipsession.create! valid_attributes
      get :edit, {:id => mentorshipsession.to_param}, valid_session
      assigns(:mentorshipsession).should eq(mentorshipsession)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Mentorshipsession" do
        expect {
          post :create, {:mentorshipsession => valid_attributes}, valid_session
        }.to change(Mentorshipsession, :count).by(1)
      end

      it "assigns a newly created mentorshipsession as @mentorshipsession" do
        post :create, {:mentorshipsession => valid_attributes}, valid_session
        assigns(:mentorshipsession).should be_a(Mentorshipsession)
        assigns(:mentorshipsession).should be_persisted
      end

      it "redirects to the created mentorshipsession" do
        post :create, {:mentorshipsession => valid_attributes}, valid_session
        response.should redirect_to(Mentorshipsession.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved mentorshipsession as @mentorshipsession" do
        # Trigger the behavior that occurs when invalid params are submitted
        Mentorshipsession.any_instance.stub(:save).and_return(false)
        post :create, {:mentorshipsession => { "mentor_id" => "invalid value" }}, valid_session
        assigns(:mentorshipsession).should be_a_new(Mentorshipsession)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Mentorshipsession.any_instance.stub(:save).and_return(false)
        post :create, {:mentorshipsession => { "mentor_id" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested mentorshipsession" do
        mentorshipsession = Mentorshipsession.create! valid_attributes
        # Assuming there are no other mentorshipsessions in the database, this
        # specifies that the Mentorshipsession created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Mentorshipsession.any_instance.should_receive(:update_attributes).with({ "mentor_id" => "" })
        put :update, {:id => mentorshipsession.to_param, :mentorshipsession => { "mentor_id" => "" }}, valid_session
      end

      it "assigns the requested mentorshipsession as @mentorshipsession" do
        mentorshipsession = Mentorshipsession.create! valid_attributes
        put :update, {:id => mentorshipsession.to_param, :mentorshipsession => valid_attributes}, valid_session
        assigns(:mentorshipsession).should eq(mentorshipsession)
      end

      it "redirects to the mentorshipsession" do
        mentorshipsession = Mentorshipsession.create! valid_attributes
        put :update, {:id => mentorshipsession.to_param, :mentorshipsession => valid_attributes}, valid_session
        response.should redirect_to(mentorshipsession)
      end
    end

    describe "with invalid params" do
      it "assigns the mentorshipsession as @mentorshipsession" do
        mentorshipsession = Mentorshipsession.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Mentorshipsession.any_instance.stub(:save).and_return(false)
        put :update, {:id => mentorshipsession.to_param, :mentorshipsession => { "mentor_id" => "invalid value" }}, valid_session
        assigns(:mentorshipsession).should eq(mentorshipsession)
      end

      it "re-renders the 'edit' template" do
        mentorshipsession = Mentorshipsession.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Mentorshipsession.any_instance.stub(:save).and_return(false)
        put :update, {:id => mentorshipsession.to_param, :mentorshipsession => { "mentor_id" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested mentorshipsession" do
      mentorshipsession = Mentorshipsession.create! valid_attributes
      expect {
        delete :destroy, {:id => mentorshipsession.to_param}, valid_session
      }.to change(Mentorshipsession, :count).by(-1)
    end

    it "redirects to the mentorshipsessions list" do
      mentorshipsession = Mentorshipsession.create! valid_attributes
      delete :destroy, {:id => mentorshipsession.to_param}, valid_session
      response.should redirect_to(mentorshipsessions_url)
    end
  end

end
